using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Typedown.Core.Contracts.Settings;

public static class TypedownDefaultShortcuts
{
    public static IReadOnlyDictionary<string, EditorShortcutKey?> All { get; } =
        new ReadOnlyDictionary<string, EditorShortcutKey?>(new Dictionary<string, EditorShortcutKey?>
        {
            ["NewFile"] = Shortcut(EditorShortcutModifierFlags.Control, 78),
            ["NewWindow"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 78),
            ["OpenFile"] = Shortcut(EditorShortcutModifierFlags.Control, 79),
            ["OpenFolder"] = null,
            ["ClearRecentFiles"] = null,
            ["Save"] = Shortcut(EditorShortcutModifierFlags.Control, 83),
            ["SaveAs"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 83),
            ["ExportSettings"] = null,
            ["Print"] = Shortcut(EditorShortcutModifierFlags.Alt | EditorShortcutModifierFlags.Shift, 80),
            ["Settings"] = Shortcut(EditorShortcutModifierFlags.Control, 188),
            ["Close"] = Shortcut(EditorShortcutModifierFlags.Control, 87),
            ["Undo"] = Shortcut(EditorShortcutModifierFlags.Control, 90),
            ["Redo"] = Shortcut(EditorShortcutModifierFlags.Control, 89),
            ["Cut"] = Shortcut(EditorShortcutModifierFlags.Control, 88),
            ["Copy"] = Shortcut(EditorShortcutModifierFlags.Control, 67),
            ["Paste"] = Shortcut(EditorShortcutModifierFlags.Control, 86),
            ["CopyAsPlainText"] = null,
            ["CopyAsMarkdown"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 67),
            ["CopyAsHTMLCode"] = null,
            ["PasteAsPlainText"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 86),
            ["Delete"] = Shortcut(EditorShortcutModifierFlags.None, 46),
            ["SelectAll"] = Shortcut(EditorShortcutModifierFlags.Control, 65),
            ["Find"] = Shortcut(EditorShortcutModifierFlags.Control, 70),
            ["FindNext"] = Shortcut(EditorShortcutModifierFlags.None, 114),
            ["FindPrevious"] = Shortcut(EditorShortcutModifierFlags.Shift, 114),
            ["Replace"] = Shortcut(EditorShortcutModifierFlags.Control, 72),
            ["Heading1"] = Shortcut(EditorShortcutModifierFlags.Control, 49),
            ["Heading2"] = Shortcut(EditorShortcutModifierFlags.Control, 50),
            ["Heading3"] = Shortcut(EditorShortcutModifierFlags.Control, 51),
            ["Heading4"] = Shortcut(EditorShortcutModifierFlags.Control, 52),
            ["Heading5"] = Shortcut(EditorShortcutModifierFlags.Control, 53),
            ["Heading6"] = Shortcut(EditorShortcutModifierFlags.Control, 54),
            ["Paragraph"] = Shortcut(EditorShortcutModifierFlags.Control, 48),
            ["IncreaseHeadingLevel"] = Shortcut(EditorShortcutModifierFlags.Control, 187),
            ["DecreaseHeadingLevel"] = Shortcut(EditorShortcutModifierFlags.Control, 189),
            ["Table"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 84),
            ["CodeFences"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 75),
            ["MathBlock"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 77),
            ["Quote"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 81),
            ["OrderedList"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 219),
            ["UnorderedList"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 221),
            ["TaskList"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 88),
            ["InsertParagraphBefore"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 13),
            ["InsertParagraphAfter"] = Shortcut(EditorShortcutModifierFlags.Control, 13),
            ["VegaChart"] = null,
            ["FlowChart"] = null,
            ["SequenceDiagram"] = null,
            ["PlantUMLDiagram"] = null,
            ["Mermaid"] = null,
            ["LinkReferences"] = null,
            ["FootNote"] = null,
            ["HorizontalLine"] = null,
            ["Toc"] = null,
            ["YAMLFrontMatter"] = null,
            ["Strong"] = Shortcut(EditorShortcutModifierFlags.Control, 66),
            ["Emphasis"] = Shortcut(EditorShortcutModifierFlags.Control, 73),
            ["Underline"] = Shortcut(EditorShortcutModifierFlags.Control, 85),
            ["InlineCode"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 192),
            ["InlineMath"] = null,
            ["Strikethrough"] = Shortcut(EditorShortcutModifierFlags.Alt | EditorShortcutModifierFlags.Shift, 53),
            ["Highlight"] = null,
            ["Hyperlink"] = Shortcut(EditorShortcutModifierFlags.Control, 75),
            ["Image"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 73),
            ["ClearFormat"] = Shortcut(EditorShortcutModifierFlags.Control, 220),
            ["SidePane"] = Shortcut(EditorShortcutModifierFlags.Control | EditorShortcutModifierFlags.Shift, 76),
            ["SourceCodeMode"] = Shortcut(EditorShortcutModifierFlags.Control, 191),
            ["FocusMode"] = Shortcut(EditorShortcutModifierFlags.None, 119),
            ["TypewriterMode"] = Shortcut(EditorShortcutModifierFlags.None, 120),
            ["StatusBar"] = null,
        });

    private static EditorShortcutKey Shortcut(EditorShortcutModifierFlags modifiers, int virtualKeyCode) =>
        new(modifiers, virtualKeyCode);
}
