-- Generated by EF Core 9.0.8 (IMigrator.GenerateScript) from the retired migration 20230226122314_InitialCreate.
-- This is the schema a fresh install created before the move to Microsoft.Data.Sqlite.
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

BEGIN TRANSACTION;
CREATE TABLE "ExportConfig" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ExportConfig" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NULL,
    "Notes" TEXT NULL,
    "Type" INTEGER NOT NULL,
    "Config" TEXT NULL
);

CREATE TABLE "FileAccessHistory" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FileAccessHistory" PRIMARY KEY AUTOINCREMENT,
    "AccessTime" TEXT NOT NULL,
    "FilePath" TEXT NULL
);

CREATE TABLE "FolderAccessHistory" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_FolderAccessHistory" PRIMARY KEY AUTOINCREMENT,
    "AccessTime" TEXT NOT NULL,
    "FolderPath" TEXT NULL
);

CREATE TABLE "ImageUploadConfig" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ImageUploadConfig" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NULL,
    "Notes" TEXT NULL,
    "IsEnable" INTEGER NOT NULL,
    "Method" INTEGER NOT NULL,
    "Config" TEXT NULL
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230226122314_InitialCreate', '9.0.8');

COMMIT;

-- EF Core 9 also creates its migration lock table on every Migrate().
CREATE TABLE IF NOT EXISTS "__EFMigrationsLock" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK___EFMigrationsLock" PRIMARY KEY,
    "Timestamp" TEXT NOT NULL
);
